name: Sync Folder to Classmate

on:
  push:
    branches:
      - main     # 👈 只要你往主仓库的 main 分支推了代码
    paths:
      - 'Humanities/Buffett-Business/**' # 👈 且改动了 Business 文件夹，机器人就会“瞬间”被唤醒
  workflow_dispatch: # 依然保留，方便你手动点

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 主仓库代码
      uses: actions/checkout@v4

    - name: 自动搬运到同学的仓库
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.SYNC_TOKEN }}
      with:
        source-directory: 'Humanities/Buffett-Business'
        destination-github-username: 'TianleXiao'
        destination-repository-name: 'obsidian-share'
        user-email: 'xiaotlinus@gmail.com'
        target-branch: main
        set-user-own-as-author: true
