name: Sync Folder to Classmate

on:
  schedule:
    - cron: '*/5 * * * *' # 👈 这行代表每隔 5 分钟，GitHub 就会自动帮你搬运一次
  workflow_dispatch: # 保留这个，方便你随时在网页上手动点“立即同步”

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 主仓库代码
      uses: actions/checkout@v4

    - name: 自动搬运到同学的仓库
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.SYNC_TOKEN }}
      with:
        source-directory: 'Humanities/Buffett-Business'
        destination-github-username: 'TianleXiao'
        destination-repository-name: 'obsidian-share'
        user-email: 'xiaotlinus@gmail.com'
        target-branch: main